WITH CTE  AS (

SELECT

TO_TIMESTAMP(STARTTIME) as STARTED_AT,
DATE(TO_TIMESTAMP(STARTTIME)) as DATE_STARTED_AT,
HOUR(TO_TIMESTAMP(STARTTIME)) as HOUR_STARTED_AT,
DAYNAME(TO_TIMESTAMP(STARTTIME)), 
{{day_type('STARTTIME')}},
{{season('STARTTIME')}}



FROM {{ source('demo', 'bike2') }}
WHERE STARTtime != 'starttime'


)
SELECT * FROM CTE
