WITH CTE  AS (

SELECT

TO_TIMESTAMP(STARTED_AT) as STARTED_AT,
DATE(TO_TIMESTAMP(STARTED_AT)) as DATE_STARTED_AT,
HOUR(TO_TIMESTAMP(STARTED_AT)) as HOUR_STARTED_AT,
DAYNAME(TO_TIMESTAMP(STARTED_AT)), 
{{day_type('STARTED_AT')}},
{{season('STARTED_AT')}}



FROM {{ source('demo', 'bike') }}
WHERE STARTED_AT != 'started_at'
LIMIT 10

)
SELECT * FROM CTE
